server:
  port: 5000 

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect 
    hibernate:
      ddl-auto: update
    show-sql: true
cloud:
  aws:
    region: us-east-2 
    credentials:
      access-key: 
      secret-key: 